In [1]:
#1
!pip install -q tensorflow

#  Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#2
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Conv1D, GlobalAveragePooling1D
from scipy import stats

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (classification_report, confusion_matrix,
                              accuracy_score, f1_score, precision_score, recall_score)
from sklearn.model_selection import train_test_split


np.random.seed(42)
tf.random.set_seed(42)
random.seed(42)

print(f" TensorFlow version: {tf.__version__}")
print(f" GPU available: {len(tf.config.list_physical_devices('GPU')) > 0}")

 TensorFlow version: 2.20.0
 GPU available: True

In [3]:
!ls /content/drive/MyDrive/GP/CSV_completeDataset

testing  training  valid

In [4]:
def load_labeled_data(base_path, window_size=10, stride=2):
    X_windows = []
    y_windows = []
    video_ids_windows = [] # New list to store video IDs for each window

    categories = {
        'Drowsy': 1,
        'Alert': 0
    }

    for category, label_value in categories.items():
        folder_path = os.path.join(base_path, category)

        if not os.path.exists(folder_path):
            print(f"Warning: Folder not found: {folder_path}")
            continue

        for filename in os.listdir(folder_path):
            if filename.endswith(".csv"):
                try:
                    file_path = os.path.join(folder_path, filename)
                    df = pd.read_csv(file_path)

                    features = df[['Duration', 'Amplitude', 'Velocity', 'Frequency']].values
                    row_labels = np.full((features.shape[0],), label_value)

                    if len(features) < window_size:
                        continue

                    # Use the filename as a unique video ID for the current file
                    video_id = filename

                    for i in range(0, len(features) - window_size + 1, stride):
                        window_features = features[i:i + window_size]
                        window_labels = row_labels[i:i + window_size]

                        mode_result = stats.mode(window_labels, keepdims=True)
                        final_label = mode_result.mode[0]

                        X_windows.append(window_features)
                        y_windows.append(final_label)
                        video_ids_windows.append(video_id) # Append video ID for each window

                except Exception as e:
                    print(f"Error processing {filename}: {e}")

    return np.array(X_windows), np.array(y_windows), np.array(video_ids_windows)

In [5]:
!ls '/content/drive/MyDrive/GP/CSV_completeDataset/'

testing  training  valid

In [6]:
train_base = '/content/drive/MyDrive/GP/CSV_completeDataset/training'
test_base   = '/content/drive/MyDrive/GP/CSV_completeDataset/testing'
val_base  = '/content/drive/MyDrive/GP/CSV_completeDataset/valid'

WINDOW_SIZE = 20
STRIDE = 2

X_train_raw, y_train, video_ids_train_raw = load_labeled_data(train_base, WINDOW_SIZE, STRIDE)
X_val_raw, y_val, video_ids_val = load_labeled_data(val_base, WINDOW_SIZE, STRIDE)
X_test_raw, y_test, video_ids_test_raw = load_labeled_data(test_base, WINDOW_SIZE, STRIDE)

print("Train:", X_train_raw.shape, y_train.shape, video_ids_train_raw.shape)
print("Val:  ", X_val_raw.shape, y_val.shape, video_ids_val.shape)
print("Test: ", X_test_raw.shape, y_test.shape, video_ids_test_raw.shape)

if X_train_raw.ndim < 3:
    print("❌ ERROR: No training windows were created!")
else:
    print(f"✅ Total Training Windows: {X_train_raw.shape[0]}")
    print(f"✅ Window Shape: {X_train_raw.shape[1]} rows x {X_train_raw.shape[2]} features")

Train: (1554, 20, 4) (1554,) (1554,)
Val:   (277, 20, 4) (277,) (277,)
Test:  (577, 20, 4) (577,) (577,)
✅ Total Training Windows: 1554
✅ Window Shape: 20 rows x 4 features

In [7]:
scaler = StandardScaler()

# TRAIN
X_train_reshaped = X_train_raw.reshape(-1, 4)
X_train_scaled = scaler.fit_transform(X_train_reshaped)
X_train = X_train_scaled.reshape(-1, WINDOW_SIZE, 4)

# VALIDATION
X_val_reshaped = X_val_raw.reshape(-1, 4)
X_val_scaled = scaler.transform(X_val_reshaped)
X_val = X_val_scaled.reshape(-1, WINDOW_SIZE, 4)

# TEST
X_test_reshaped = X_test_raw.reshape(-1, 4)
X_test_scaled = scaler.transform(X_test_reshaped)
X_test = X_test_scaled.reshape(-1, WINDOW_SIZE, 4)

print("Scaled Train:", X_train.shape)
print("Scaled Val:  ", X_val.shape)
print("Scaled Test: ", X_test.shape)

Scaled Train: (1554, 20, 4)
Scaled Val:   (277, 20, 4)
Scaled Test:  (577, 20, 4)

In [ ]:
gru_model = Sequential([
    GRU(128, return_sequences=True, input_shape=(WINDOW_SIZE, 4)),
    GRU(16),
    Dropout(0.3),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

gru_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

gru_model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_44"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru_44 (GRU)                    │ (None, 20, 128)        │        51,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_45 (GRU)                    │ (None, 16)             │         7,008 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_88 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_88 (Dense)                │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_89 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 58,753 (229.50 KB)

 Trainable params: 58,753 (229.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
gru_history = gru_model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=20,
    batch_size=32,
    verbose=1
)

gru_save_path = '/content/drive/MyDrive/GP/LstmModels/best_gru_drowsy_model.h5'
gru_model.save(gru_save_path)

print(f"🚀 GRU model saved successfully to: {gru_save_path}")

Epoch 1/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.5927 - loss: 0.6769 - val_accuracy: 0.6643 - val_loss: 0.6683
Epoch 2/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8179 - loss: 0.6105 - val_accuracy: 0.7617 - val_loss: 0.6082
Epoch 3/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8752 - loss: 0.5005 - val_accuracy: 0.7978 - val_loss: 0.5032
Epoch 4/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9254 - loss: 0.3219 - val_accuracy: 0.8087 - val_loss: 0.4449
Epoch 5/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9434 - loss: 0.1910 - val_accuracy: 0.8123 - val_loss: 0.4838
Epoch 6/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9575 - loss: 0.1505 - val_accuracy: 0.8159 - val_loss: 0.5125
Epoch 7/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9614 - loss: 0.1269 - val_accuracy: 0.8195 - val_loss: 0.5392
Epoch 8/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9672 - loss: 0.1117 - val_accuracy: 0.8231 - val_loss: 0.5702
Epoch 9/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9723 - loss: 0.0940 - val_accuracy: 0.8267 - val_loss: 0.5997
Epoch 10/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9749 - loss: 0.0887 - val_accuracy: 0.8231 - val_loss: 0.6097
Epoch 11/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9775 - loss: 0.0777 - val_accuracy: 0.8231 - val_loss: 0.6294
Epoch 12/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9768 - loss: 0.0707 - val_accuracy: 0.8159 - val_loss: 0.6425
Epoch 13/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9833 - loss: 0.0669 - val_accuracy: 0.8159 - val_loss: 0.6612
Epoch 14/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9833 - loss: 0.0632 - val_accuracy: 0.8159 - val_loss: 0.6885
Epoch 15/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9833 - loss: 0.0601 - val_accuracy: 0.8159 - val_loss: 0.7164
Epoch 16/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9852 - loss: 0.0557 - val_accuracy: 0.8159 - val_loss: 0.7430
Epoch 17/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9852 - loss: 0.0556 - val_accuracy: 0.8123 - val_loss: 0.7681
Epoch 18/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9839 - loss: 0.0523 - val_accuracy: 0.8195 - val_loss: 0.7708
Epoch 19/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9884 - loss: 0.0485 - val_accuracy: 0.8195 - val_loss: 0.8073
Epoch 20/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9858 - loss: 0.0501 - val_accuracy: 0.8195 - val_loss: 0.8204

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

🚀 GRU model saved successfully to: /content/drive/MyDrive/GP/LstmModels/best_gru_drowsy_model.h5

In [ ]:
tcn_model = Sequential([
    Conv1D(64, kernel_size=3, dilation_rate=1, padding='causal', activation='relu', input_shape=(WINDOW_SIZE, 4)),
    Dropout(0.3),

    Conv1D(64, kernel_size=3, dilation_rate=2, padding='causal', activation='relu'),
    Dropout(0.3),

    Conv1D(32, kernel_size=3, dilation_rate=4, padding='causal', activation='relu'),
    Dropout(0.3),

    GlobalAveragePooling1D(),

    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

tcn_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

tcn_model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_45"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_66 (Conv1D)              │ (None, 20, 64)         │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_89 (Dropout)            │ (None, 20, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_67 (Conv1D)              │ (None, 20, 64)         │        12,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_90 (Dropout)            │ (None, 20, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_68 (Conv1D)              │ (None, 20, 32)         │         6,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_91 (Dropout)            │ (None, 20, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_22     │ (None, 32)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_90 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_91 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,905 (77.75 KB)

 Trainable params: 19,905 (77.75 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
tcn_history = tcn_model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=20,
    batch_size=32,
    verbose=1
)

tcn_save_path = '/content/drive/MyDrive/GP/LstmModels/best_tcn_drowsy_model.h5'
tcn_model.save(tcn_save_path)

print(f"🚀 TCN model saved successfully to: {tcn_save_path}")

Epoch 1/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 10s 83ms/step - accuracy: 0.5727 - loss: 0.6842 - val_accuracy: 0.5596 - val_loss: 0.6752
Epoch 2/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6287 - loss: 0.6485 - val_accuracy: 0.6643 - val_loss: 0.6285
Epoch 3/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8308 - loss: 0.5705 - val_accuracy: 0.8014 - val_loss: 0.5422
Epoch 4/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9073 - loss: 0.4489 - val_accuracy: 0.8195 - val_loss: 0.4518
Epoch 5/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9221 - loss: 0.3294 - val_accuracy: 0.8267 - val_loss: 0.4065
Epoch 6/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9356 - loss: 0.2478 - val_accuracy: 0.8231 - val_loss: 0.4055
Epoch 7/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9414 - loss: 0.2042 - val_accuracy: 0.8195 - val_loss: 0.4298
Epoch 8/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9479 - loss: 0.1753 - val_accuracy: 0.8195 - val_loss: 0.4572
Epoch 9/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9459 - loss: 0.1569 - val_accuracy: 0.8195 - val_loss: 0.4983
Epoch 10/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9524 - loss: 0.1420 - val_accuracy: 0.8267 - val_loss: 0.5283
Epoch 11/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9517 - loss: 0.1351 - val_accuracy: 0.8267 - val_loss: 0.5532
Epoch 12/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9530 - loss: 0.1253 - val_accuracy: 0.8267 - val_loss: 0.5897
Epoch 13/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9543 - loss: 0.1206 - val_accuracy: 0.8267 - val_loss: 0.6070
Epoch 14/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9575 - loss: 0.1203 - val_accuracy: 0.8267 - val_loss: 0.6281
Epoch 15/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9562 - loss: 0.1169 - val_accuracy: 0.8267 - val_loss: 0.6495
Epoch 16/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9569 - loss: 0.1115 - val_accuracy: 0.8231 - val_loss: 0.6872
Epoch 17/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9640 - loss: 0.0992 - val_accuracy: 0.8267 - val_loss: 0.6899
Epoch 18/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9575 - loss: 0.1057 - val_accuracy: 0.8231 - val_loss: 0.7113
Epoch 19/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9633 - loss: 0.0933 - val_accuracy: 0.8231 - val_loss: 0.7332
Epoch 20/20
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9627 - loss: 0.0980 - val_accuracy: 0.8231 - val_loss: 0.7381

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

🚀 TCN model saved successfully to: /content/drive/MyDrive/GP/LstmModels/best_tcn_drowsy_model.h5

In [ ]:
def evaluate_model_by_file(model, model_name, test_base, scaler, window_size=10, stride=2):
    total_windows_tested = 0
    correct_windows = 0

    total_videos_tested = 0
    correct_videos = 0

    print(f"\n========== {model_name} RESULTS ==========")
    print(f"{'File Name':<25} | {'Label':<8} | {'Window Acc':<12} | {'Drowsy %':<10} | {'Verdict':<8} | {'Status'}")
    print("-" * 95)

    for category in ['Drowsy', 'Alert']:
        folder_path = os.path.join(test_base, category)

        if not os.path.exists(folder_path):
            print(f"Warning: Folder not found: {folder_path}")
            continue

        true_val = 1 if category == 'Drowsy' else 0

        for filename in os.listdir(folder_path):
            if filename.endswith(".csv"):
                file_path = os.path.join(folder_path, filename)
                df_file = pd.read_csv(file_path)

                feats = df_file[['Duration', 'Amplitude', 'Velocity', 'Frequency']].values

                if len(feats) < window_size:
                    continue

                file_windows = []

                for i in range(0, len(feats) - window_size + 1, stride):
                    file_windows.append(feats[i:i + window_size])

                X_file = np.array(file_windows)

                X_file_reshaped = X_file.reshape(-1, 4)
                X_file_scaled = scaler.transform(X_file_reshaped)
                X_file_final = X_file_scaled.reshape(-1, window_size, 4)

                file_preds = model.predict(X_file_final, verbose=0)
                file_rounded = (file_preds > 0.5).astype(int).flatten()

                # Window accuracy for this file
                file_window_acc = np.mean(file_rounded == true_val) * 100

                total_windows_tested += len(file_rounded)
                correct_windows += np.sum(file_rounded == true_val)

                # Video-level decision
                drowsy_percent = (np.sum(file_rounded) / len(file_rounded)) * 100
                verdict_val = 1 if drowsy_percent > 50 else 0

                total_videos_tested += 1

                if verdict_val == true_val:
                    correct_videos += 1

                status = "✅" if verdict_val == true_val else "❌"
                verdict_text = "DROWSY" if verdict_val == 1 else "ALERT"

                print(
                    f"{filename[:25]:<25} | "
                    f"{category:<8} | "
                    f"{file_window_acc:>9.1f}% | "
                    f"{drowsy_percent:>8.1f}% | "
                    f"{verdict_text:<8} | "
                    f"{status}"
                )

    window_accuracy = (correct_windows / total_windows_tested) * 100 if total_windows_tested > 0 else 0
    video_accuracy = (correct_videos / total_videos_tested) * 100 if total_videos_tested > 0 else 0

    print("\n" + "=" * 45)
    print(f"{model_name} TOTAL WINDOW ACCURACY: {window_accuracy:.2f}%")
    print(f"{model_name} TOTAL VIDEO ACCURACY:  {video_accuracy:.2f}%")
    print("=" * 45)

    return window_accuracy, video_accuracy

In [ ]:
gru_window_acc, gru_video_acc = evaluate_model_by_file(
    gru_model,
    "GRU",
    test_base,
    scaler,
    WINDOW_SIZE,
    STRIDE
)

tcn_window_acc, tcn_video_acc = evaluate_model_by_file(
    tcn_model,
    "TCN",
    test_base,
    scaler,
    WINDOW_SIZE,
    STRIDE
)

========== GRU RESULTS ==========
File Name                 | Label    | Window Acc   | Drowsy %   | Verdict  | Status
-----------------------------------------------------------------------------------------------
D022_20260513_190626_fram | Drowsy   |     100.0% |    100.0% | DROWSY   | ✅
D023_20260513_195650_fram | Drowsy   |     100.0% |    100.0% | DROWSY   | ✅
D024_20260513_212814_fram | Drowsy   |      93.5% |     93.5% | DROWSY   | ✅
D025_20260513_233342_fram | Drowsy   |      25.0% |     25.0% | ALERT    | ❌
D026_20260514_025307_fram | Drowsy   |      87.3% |     87.3% | DROWSY   | ✅
A022_20260513_190541_fram | Alert    |       0.0% |    100.0% | DROWSY   | ❌
A023_20260513_195602_fram | Alert    |      76.8% |     23.2% | ALERT    | ✅
A024_20260513_212736_fram | Alert    |       0.0% |    100.0% | DROWSY   | ❌
A025_20260513_233235_fram | Alert    |      87.6% |     12.4% | ALERT    | ✅
A026_20260514_025227_fram | Alert    |      98.7% |      1.3% | ALERT    | ✅

=============================================
GRU TOTAL WINDOW ACCURACY: 68.46%
GRU TOTAL VIDEO ACCURACY:  70.00%
=============================================

========== TCN RESULTS ==========
File Name                 | Label    | Window Acc   | Drowsy %   | Verdict  | Status
-----------------------------------------------------------------------------------------------
D022_20260513_190626_fram | Drowsy   |     100.0% |    100.0% | DROWSY   | ✅
D023_20260513_195650_fram | Drowsy   |     100.0% |    100.0% | DROWSY   | ✅
D024_20260513_212814_fram | Drowsy   |      85.7% |     85.7% | DROWSY   | ✅
D025_20260513_233342_fram | Drowsy   |      13.5% |     13.5% | ALERT    | ❌
D026_20260514_025307_fram | Drowsy   |      81.8% |     81.8% | DROWSY   | ✅
A022_20260513_190541_fram | Alert    |       0.0% |    100.0% | DROWSY   | ❌
A023_20260513_195602_fram | Alert    |      81.2% |     18.8% | ALERT    | ✅
A024_20260513_212736_fram | Alert    |       0.0% |    100.0% | DROWSY   | ❌
A025_20260513_233235_fram | Alert    |      94.4% |      5.6% | ALERT    | ✅
A026_20260514_025227_fram | Alert    |      94.7% |      5.3% | ALERT    | ✅

=============================================
TCN TOTAL WINDOW ACCURACY: 66.90%
TCN TOTAL VIDEO ACCURACY:  70.00%
=============================================

In [ ]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [ ]:
import optuna
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    GRU,
    Dense,
    Dropout
)

In [ ]:
def objective_gru(trial):

    # Hyperparameters to tune
    gru_units_1 = trial.suggest_int("gru_units_1", 32, 128)
    gru_units_2 = trial.suggest_int("gru_units_2", 8, 64)

    dropout_rate = trial.suggest_float("dropout", 0.1, 0.5)

    learning_rate = trial.suggest_float(
        "learning_rate",
        1e-5,
        1e-3,
        log=True
    )

    batch_size = trial.suggest_categorical(
        "batch_size",
        [16, 32, 64]
    )

    # Build model
    model = Sequential([

        GRU(
            gru_units_1,
            return_sequences=True,
            input_shape=(WINDOW_SIZE, 4)
        ),

        GRU(gru_units_2),

        Dropout(dropout_rate),

        Dense(16, activation='relu'),

        Dense(1, activation='sigmoid')

    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=learning_rate
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    # Train
    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=10,
        batch_size=batch_size,
        verbose=0
    )

    # Return BEST validation accuracy
    best_val_acc = max(history.history['val_accuracy'])

    return best_val_acc

In [ ]:
study_gru = optuna.create_study(direction="maximize")

study_gru.optimize(
    objective_gru,
    n_trials=20
)

[I 2026-06-02 12:05:02,393] A new study created in memory with name: no-name-bbd541b0-c111-4033-8d77-30a2c2d1207f
/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
[I 2026-06-02 12:05:29,580] Trial 0 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 87, 'gru_units_2': 21, 'dropout': 0.1801192285823516, 'learning_rate': 6.340961327019132e-05, 'batch_size': 16}. Best is trial 0 with value: 0.8303248882293701.
[I 2026-06-02 12:05:40,095] Trial 1 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 97, 'gru_units_2': 47, 'dropout': 0.23155507209346293, 'learning_rate': 0.000622281437501698, 'batch_size': 32}. Best is trial 0 with value: 0.8303248882293701.
[I 2026-06-02 12:05:49,544] Trial 2 finished with value: 0.8411552309989929 and parameters: {'gru_units_1': 41, 'gru_units_2': 49, 'dropout': 0.17577537013775327, 'learning_rate': 0.0002623867394540794, 'batch_size': 32}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:06:02,503] Trial 3 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 74, 'gru_units_2': 53, 'dropout': 0.16368555381005848, 'learning_rate': 0.00010404232374730637, 'batch_size': 16}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:06:09,194] Trial 4 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 57, 'gru_units_2': 18, 'dropout': 0.35941827937009674, 'learning_rate': 0.0008225037144996946, 'batch_size': 64}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:06:17,817] Trial 5 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 37, 'gru_units_2': 15, 'dropout': 0.18499177576701423, 'learning_rate': 7.692717649881002e-05, 'batch_size': 32}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:06:31,103] Trial 6 finished with value: 0.8375450968742371 and parameters: {'gru_units_1': 122, 'gru_units_2': 64, 'dropout': 0.28208549419448553, 'learning_rate': 5.91924818601981e-05, 'batch_size': 16}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:06:39,712] Trial 7 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 95, 'gru_units_2': 26, 'dropout': 0.34661184423812597, 'learning_rate': 5.1390976042670305e-05, 'batch_size': 32}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:06:46,289] Trial 8 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 108, 'gru_units_2': 26, 'dropout': 0.3322588931282202, 'learning_rate': 0.0008238658839498413, 'batch_size': 64}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:06:54,640] Trial 9 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 85, 'gru_units_2': 40, 'dropout': 0.16434432654127545, 'learning_rate': 0.0004168622722961972, 'batch_size': 32}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:07:05,996] Trial 10 finished with value: 0.7653429508209229 and parameters: {'gru_units_1': 37, 'gru_units_2': 35, 'dropout': 0.49026697034279176, 'learning_rate': 1.642270318006559e-05, 'batch_size': 32}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:07:20,067] Trial 11 finished with value: 0.8194946050643921 and parameters: {'gru_units_1': 116, 'gru_units_2': 62, 'dropout': 0.2904353484166284, 'learning_rate': 0.00022363690262734858, 'batch_size': 16}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:07:34,404] Trial 12 finished with value: 0.8158844709396362 and parameters: {'gru_units_1': 125, 'gru_units_2': 64, 'dropout': 0.2512675026111253, 'learning_rate': 1.9781166454141566e-05, 'batch_size': 16}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:07:48,313] Trial 13 finished with value: 0.826714813709259 and parameters: {'gru_units_1': 60, 'gru_units_2': 54, 'dropout': 0.446996719968201, 'learning_rate': 0.00022709695333761847, 'batch_size': 16}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:07:56,923] Trial 14 finished with value: 0.7220216393470764 and parameters: {'gru_units_1': 55, 'gru_units_2': 53, 'dropout': 0.10070119260660729, 'learning_rate': 3.477562109962207e-05, 'batch_size': 64}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:08:05,343] Trial 15 finished with value: 0.833935022354126 and parameters: {'gru_units_1': 71, 'gru_units_2': 43, 'dropout': 0.40276789219085174, 'learning_rate': 0.00015966208964728987, 'batch_size': 32}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:08:20,314] Trial 16 finished with value: 0.8050541281700134 and parameters: {'gru_units_1': 126, 'gru_units_2': 58, 'dropout': 0.11491291822207547, 'learning_rate': 1.0312962271036993e-05, 'batch_size': 16}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:08:29,952] Trial 17 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 45, 'gru_units_2': 47, 'dropout': 0.26551196112554376, 'learning_rate': 0.0001306889975847644, 'batch_size': 32}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:08:44,528] Trial 18 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 109, 'gru_units_2': 58, 'dropout': 0.2106088638449528, 'learning_rate': 0.00042460354444763293, 'batch_size': 16}. Best is trial 2 with value: 0.8411552309989929.
[I 2026-06-02 12:08:51,294] Trial 19 finished with value: 0.5920577645301819 and parameters: {'gru_units_1': 66, 'gru_units_2': 35, 'dropout': 0.3004086652293856, 'learning_rate': 3.364465592704992e-05, 'batch_size': 64}. Best is trial 2 with value: 0.8411552309989929.

In [ ]:
print("Best Trial:")
print(study_gru.best_trial)

print("\nBest Params:")
print(study_gru.best_params)

print("\nBest Validation Accuracy:")
print(study_gru.best_value)

Best Trial:
FrozenTrial(number=2, state=<TrialState.COMPLETE: 1>, values=[0.8411552309989929], datetime_start=datetime.datetime(2026, 6, 2, 12, 5, 40, 97592), datetime_complete=datetime.datetime(2026, 6, 2, 12, 5, 49, 544874), params={'gru_units_1': 41, 'gru_units_2': 49, 'dropout': 0.17577537013775327, 'learning_rate': 0.0002623867394540794, 'batch_size': 32}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'gru_units_1': IntDistribution(high=128, log=False, low=32, step=1), 'gru_units_2': IntDistribution(high=64, log=False, low=8, step=1), 'dropout': FloatDistribution(high=0.5, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.001, log=True, low=1e-05, step=None), 'batch_size': CategoricalDistribution(choices=(16, 32, 64))}, trial_id=2, value=None)

Best Params:
{'gru_units_1': 41, 'gru_units_2': 49, 'dropout': 0.17577537013775327, 'learning_rate': 0.0002623867394540794, 'batch_size': 32}

Best Validation Accuracy:
0.8411552309989929

In [ ]:
best_gru_model = Sequential([
    GRU(88, return_sequences=True, input_shape=(WINDOW_SIZE, 4)),
    GRU(30),
    Dropout(0.4176403928249539),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

best_gru_model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=5.8407380914947864e-05
    ),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

best_gru_history = best_gru_model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=30,
    batch_size=16,
    verbose=1
)

save_path = '/content/drive/MyDrive/GP/LstmModels/final_best_gru_optuna.h5'
best_gru_model.save(save_path)

print(f"🚀 Final tuned GRU model saved to: {save_path}")

Epoch 1/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.5695 - loss: 0.6861 - val_accuracy: 0.6787 - val_loss: 0.6788
Epoch 2/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7902 - loss: 0.6417 - val_accuracy: 0.7726 - val_loss: 0.6380
Epoch 3/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8694 - loss: 0.5735 - val_accuracy: 0.8123 - val_loss: 0.5763
Epoch 4/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9060 - loss: 0.4564 - val_accuracy: 0.8267 - val_loss: 0.4547
Epoch 5/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9311 - loss: 0.2729 - val_accuracy: 0.8123 - val_loss: 0.4028
Epoch 6/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9511 - loss: 0.1729 - val_accuracy: 0.8267 - val_loss: 0.4464
Epoch 7/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.9588 - loss: 0.1440 - val_accuracy: 0.8195 - val_loss: 0.4702
Epoch 8/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9627 - loss: 0.1242 - val_accuracy: 0.8195 - val_loss: 0.5027
Epoch 9/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.9653 - loss: 0.1114 - val_accuracy: 0.8195 - val_loss: 0.5274
Epoch 10/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.9698 - loss: 0.0993 - val_accuracy: 0.8195 - val_loss: 0.5351
Epoch 11/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 0.9710 - loss: 0.0885 - val_accuracy: 0.8231 - val_loss: 0.5697
Epoch 12/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 0.9755 - loss: 0.0854 - val_accuracy: 0.8231 - val_loss: 0.5825
Epoch 13/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 0.9749 - loss: 0.0774 - val_accuracy: 0.8231 - val_loss: 0.5952
Epoch 14/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.9768 - loss: 0.0722 - val_accuracy: 0.8195 - val_loss: 0.6096
Epoch 15/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9781 - loss: 0.0683 - val_accuracy: 0.8195 - val_loss: 0.6397
Epoch 16/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9775 - loss: 0.0679 - val_accuracy: 0.8195 - val_loss: 0.6472
Epoch 17/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9775 - loss: 0.0624 - val_accuracy: 0.8195 - val_loss: 0.6597
Epoch 18/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9794 - loss: 0.0593 - val_accuracy: 0.8231 - val_loss: 0.6746
Epoch 19/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9807 - loss: 0.0579 - val_accuracy: 0.8231 - val_loss: 0.6881
Epoch 20/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9833 - loss: 0.0553 - val_accuracy: 0.8159 - val_loss: 0.7033
Epoch 21/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9833 - loss: 0.0534 - val_accuracy: 0.8159 - val_loss: 0.7191
Epoch 22/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9852 - loss: 0.0531 - val_accuracy: 0.8159 - val_loss: 0.7348
Epoch 23/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9858 - loss: 0.0490 - val_accuracy: 0.8159 - val_loss: 0.7456
Epoch 24/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9871 - loss: 0.0470 - val_accuracy: 0.8159 - val_loss: 0.7591
Epoch 25/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9878 - loss: 0.0461 - val_accuracy: 0.8159 - val_loss: 0.7757
Epoch 26/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9871 - loss: 0.0453 - val_accuracy: 0.8195 - val_loss: 0.7920
Epoch 27/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9865 - loss: 0.0465 - val_accuracy: 0.8195 - val_loss: 0.8051
Epoch 28/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9891 - loss: 0.0430 - val_accuracy: 0.8195 - val_loss: 0.8184
Epoch 29/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9891 - loss: 0.0409 - val_accuracy: 0.8195 - val_loss: 0.8322
Epoch 30/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9897 - loss: 0.0438 - val_accuracy: 0.8159 - val_loss: 0.8471

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

🚀 Final tuned GRU model saved to: /content/drive/MyDrive/GP/LstmModels/final_best_gru_optuna.h5

In [ ]:
gru_window_acc, gru_video_acc = evaluate_model_by_file(
    best_gru_model,
    "FINAL OPTUNA GRU",
    test_base,
    scaler,
    WINDOW_SIZE,
    STRIDE
)

========== FINAL OPTUNA GRU RESULTS ==========
File Name                 | Label    | Window Acc   | Drowsy %   | Verdict  | Status
-----------------------------------------------------------------------------------------------
D022_20260513_190626_fram | Drowsy   |     100.0% |    100.0% | DROWSY   | ✅
D023_20260513_195650_fram | Drowsy   |     100.0% |    100.0% | DROWSY   | ✅
D024_20260513_212814_fram | Drowsy   |      96.1% |     96.1% | DROWSY   | ✅
D025_20260513_233342_fram | Drowsy   |      25.0% |     25.0% | ALERT    | ❌
D026_20260514_025307_fram | Drowsy   |      87.3% |     87.3% | DROWSY   | ✅
A022_20260513_190541_fram | Alert    |       0.0% |    100.0% | DROWSY   | ❌
A023_20260513_195602_fram | Alert    |      76.8% |     23.2% | ALERT    | ✅
A024_20260513_212736_fram | Alert    |       0.0% |    100.0% | DROWSY   | ❌
A025_20260513_233235_fram | Alert    |      84.3% |     15.7% | ALERT    | ✅
A026_20260514_025227_fram | Alert    |      97.3% |      2.7% | ALERT    | ✅

=============================================
FINAL OPTUNA GRU TOTAL WINDOW ACCURACY: 68.11%
FINAL OPTUNA GRU TOTAL VIDEO ACCURACY:  70.00%
=============================================

In [ ]:
def objective_tcn(trial):

    filters_1 = trial.suggest_categorical("filters_1", [32, 64, 96, 128])
    filters_2 = trial.suggest_categorical("filters_2", [32, 64, 96])
    filters_3 = trial.suggest_categorical("filters_3", [16, 32, 64])

    kernel_size = trial.suggest_categorical("kernel_size", [2, 3, 5])

    dropout_rate = trial.suggest_float("dropout", 0.1, 0.5)

    dense_units = trial.suggest_categorical("dense_units", [8, 16, 32])

    learning_rate = trial.suggest_float(
        "learning_rate",
        1e-5,
        1e-3,
        log=True
    )

    batch_size = trial.suggest_categorical(
        "batch_size",
        [16, 32, 64]
    )

    model = Sequential([
        Conv1D(
            filters_1,
            kernel_size=kernel_size,
            dilation_rate=1,
            padding='causal',
            activation='relu',
            input_shape=(WINDOW_SIZE, 4)
        ),
        Dropout(dropout_rate),

        Conv1D(
            filters_2,
            kernel_size=kernel_size,
            dilation_rate=2,
            padding='causal',
            activation='relu'
        ),
        Dropout(dropout_rate),

        Conv1D(
            filters_3,
            kernel_size=kernel_size,
            dilation_rate=4,
            padding='causal',
            activation='relu'
        ),
        Dropout(dropout_rate),

        GlobalAveragePooling1D(),

        Dense(dense_units, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=learning_rate
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=10,
        batch_size=batch_size,
        verbose=0
    )

    best_val_acc = max(history.history['val_accuracy'])

    return best_val_acc

In [ ]:
study_tcn = optuna.create_study(direction="maximize")

study_tcn.optimize(
    objective_tcn,
    n_trials=20
)

[I 2026-06-02 12:09:45,790] A new study created in memory with name: no-name-e0c18925-362c-4c82-8e6d-5eca40ea561f
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-06-02 12:09:58,728] Trial 0 finished with value: 0.6642599105834961 and parameters: {'filters_1': 128, 'filters_2': 32, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.27855093172530165, 'dense_units': 8, 'learning_rate': 2.8694029555785238e-05, 'batch_size': 32}. Best is trial 0 with value: 0.6642599105834961.
[I 2026-06-02 12:10:12,057] Trial 1 finished with value: 0.8014440536499023 and parameters: {'filters_1': 128, 'filters_2': 96, 'filters_3': 16, 'kernel_size': 5, 'dropout': 0.2345185239161074, 'dense_units': 32, 'learning_rate': 4.153519565698037e-05, 'batch_size': 64}. Best is trial 1 with value: 0.8014440536499023.
[I 2026-06-02 12:10:24,753] Trial 2 finished with value: 0.8194946050643921 and parameters: {'filters_1': 128, 'filters_2': 96, 'filters_3': 16, 'kernel_size': 3, 'dropout': 0.32825796508963767, 'dense_units': 32, 'learning_rate': 0.00012035967260217889, 'batch_size': 64}. Best is trial 2 with value: 0.8194946050643921.
[I 2026-06-02 12:10:37,115] Trial 3 finished with value: 0.7978339195251465 and parameters: {'filters_1': 64, 'filters_2': 32, 'filters_3': 32, 'kernel_size': 5, 'dropout': 0.2753123312774579, 'dense_units': 8, 'learning_rate': 3.6920924342305773e-05, 'batch_size': 64}. Best is trial 2 with value: 0.8194946050643921.
[I 2026-06-02 12:10:51,008] Trial 4 finished with value: 0.8411552309989929 and parameters: {'filters_1': 96, 'filters_2': 96, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.460048767275383, 'dense_units': 16, 'learning_rate': 6.58959448745374e-05, 'batch_size': 16}. Best is trial 4 with value: 0.8411552309989929.
[I 2026-06-02 12:11:05,091] Trial 5 finished with value: 0.8375450968742371 and parameters: {'filters_1': 32, 'filters_2': 96, 'filters_3': 32, 'kernel_size': 3, 'dropout': 0.3214100991235523, 'dense_units': 8, 'learning_rate': 0.00025994168411900675, 'batch_size': 32}. Best is trial 4 with value: 0.8411552309989929.
[I 2026-06-02 12:11:20,914] Trial 6 finished with value: 0.826714813709259 and parameters: {'filters_1': 32, 'filters_2': 32, 'filters_3': 32, 'kernel_size': 5, 'dropout': 0.23184240735482012, 'dense_units': 16, 'learning_rate': 4.990400298029324e-05, 'batch_size': 16}. Best is trial 4 with value: 0.8411552309989929.
[I 2026-06-02 12:11:36,842] Trial 7 finished with value: 0.8231046795845032 and parameters: {'filters_1': 64, 'filters_2': 32, 'filters_3': 16, 'kernel_size': 2, 'dropout': 0.12419460108415481, 'dense_units': 32, 'learning_rate': 4.832980020395435e-05, 'batch_size': 16}. Best is trial 4 with value: 0.8411552309989929.
[I 2026-06-02 12:11:48,843] Trial 8 finished with value: 0.8303248882293701 and parameters: {'filters_1': 32, 'filters_2': 64, 'filters_3': 16, 'kernel_size': 5, 'dropout': 0.36933870544539693, 'dense_units': 32, 'learning_rate': 0.00024192148210498682, 'batch_size': 64}. Best is trial 4 with value: 0.8411552309989929.
[I 2026-06-02 12:12:01,494] Trial 9 finished with value: 0.8050541281700134 and parameters: {'filters_1': 128, 'filters_2': 32, 'filters_3': 32, 'kernel_size': 2, 'dropout': 0.4989640178916903, 'dense_units': 32, 'learning_rate': 6.233228785872706e-05, 'batch_size': 32}. Best is trial 4 with value: 0.8411552309989929.
[I 2026-06-02 12:12:17,807] Trial 10 finished with value: 0.8447653651237488 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.4537713359407464, 'dense_units': 16, 'learning_rate': 0.0007589233977699791, 'batch_size': 16}. Best is trial 10 with value: 0.8447653651237488.
[I 2026-06-02 12:12:31,408] Trial 11 finished with value: 0.8519855737686157 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.4705924383482873, 'dense_units': 16, 'learning_rate': 0.0009796357896900579, 'batch_size': 16}. Best is trial 11 with value: 0.8519855737686157.
[I 2026-06-02 12:12:47,442] Trial 12 finished with value: 0.8375450968742371 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.4263373117075017, 'dense_units': 16, 'learning_rate': 0.0008798684911483199, 'batch_size': 16}. Best is trial 11 with value: 0.8519855737686157.
[I 2026-06-02 12:13:00,922] Trial 13 finished with value: 0.8303248882293701 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.4089693234495691, 'dense_units': 16, 'learning_rate': 0.0008763163857293569, 'batch_size': 16}. Best is trial 11 with value: 0.8519855737686157.
[I 2026-06-02 12:13:14,140] Trial 14 finished with value: 0.8375450968742371 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.4736257060364771, 'dense_units': 16, 'learning_rate': 0.0004456281946777568, 'batch_size': 16}. Best is trial 11 with value: 0.8519855737686157.
[I 2026-06-02 12:13:27,037] Trial 15 finished with value: 0.826714813709259 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.39674236416649145, 'dense_units': 16, 'learning_rate': 1.1915851064100445e-05, 'batch_size': 16}. Best is trial 11 with value: 0.8519855737686157.
[I 2026-06-02 12:13:40,632] Trial 16 finished with value: 0.8447653651237488 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 3, 'dropout': 0.44367655640383985, 'dense_units': 16, 'learning_rate': 0.00048451541082985514, 'batch_size': 16}. Best is trial 11 with value: 0.8519855737686157.
[I 2026-06-02 12:13:53,867] Trial 17 finished with value: 0.8375450968742371 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.3635087151623778, 'dense_units': 16, 'learning_rate': 0.00045974432994583855, 'batch_size': 16}. Best is trial 11 with value: 0.8519855737686157.
[I 2026-06-02 12:14:09,662] Trial 18 finished with value: 0.833935022354126 and parameters: {'filters_1': 96, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 2, 'dropout': 0.4961854027308957, 'dense_units': 16, 'learning_rate': 0.000983793052137705, 'batch_size': 16}. Best is trial 11 with value: 0.8519855737686157.
[I 2026-06-02 12:14:21,480] Trial 19 finished with value: 0.8303248882293701 and parameters: {'filters_1': 64, 'filters_2': 64, 'filters_3': 64, 'kernel_size': 3, 'dropout': 0.12419647847792298, 'dense_units': 16, 'learning_rate': 0.0002086256698132605, 'batch_size': 32}. Best is trial 11 with value: 0.8519855737686157.

In [ ]:
print("Best TCN Trial:")
print(study_tcn.best_trial)

print("\nBest TCN Params:")
print(study_tcn.best_params)

print("\nBest TCN Validation Accuracy:")
print(study_tcn.best_value)

Best TCN Trial:
FrozenTrial(number=12, state=<TrialState.COMPLETE: 1>, values=[0.6949740052223206], datetime_start=datetime.datetime(2026, 6, 2, 11, 59, 18, 957170), datetime_complete=datetime.datetime(2026, 6, 2, 11, 59, 33, 64493), params={'filters_1': 32, 'filters_2': 32, 'filters_3': 16, 'kernel_size': 5, 'dropout': 0.49876496979911766, 'dense_units': 16, 'learning_rate': 0.0008934228053411201, 'batch_size': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'filters_1': CategoricalDistribution(choices=(32, 64, 96, 128)), 'filters_2': CategoricalDistribution(choices=(32, 64, 96)), 'filters_3': CategoricalDistribution(choices=(16, 32, 64)), 'kernel_size': CategoricalDistribution(choices=(2, 3, 5)), 'dropout': FloatDistribution(high=0.5, log=False, low=0.1, step=None), 'dense_units': CategoricalDistribution(choices=(8, 16, 32)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=1e-05, step=None), 'batch_size': CategoricalDistribution(choices=(16, 32, 64))}, trial_id=12, value=None)

Best TCN Params:
{'filters_1': 32, 'filters_2': 32, 'filters_3': 16, 'kernel_size': 5, 'dropout': 0.49876496979911766, 'dense_units': 16, 'learning_rate': 0.0008934228053411201, 'batch_size': 16}

Best TCN Validation Accuracy:
0.6949740052223206

In [ ]:
best_tcn_model = Sequential([
    Conv1D(
        32,
        kernel_size=5,
        dilation_rate=1,
        padding='causal',
        activation='relu',
        input_shape=(WINDOW_SIZE, 4)
    ),
    Dropout(0.2986960433074547),

    Conv1D(
        96,
        kernel_size=5,
        dilation_rate=2,
        padding='causal',
        activation='relu'
    ),
    Dropout(0.2986960433074547),

    Conv1D(
        32,
        kernel_size=5,
        dilation_rate=4,
        padding='causal',
        activation='relu'
    ),
    Dropout(0.2986960433074547),

    GlobalAveragePooling1D(),

    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

best_tcn_model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.0009854876557513254
    ),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

best_tcn_history = best_tcn_model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=30,
    batch_size=16,
    verbose=1
)

save_path = '/content/drive/MyDrive/GP/LstmModels/final_best_tcn_optuna.h5'
best_tcn_model.save(save_path)

print(f"🚀 Final tuned TCN model saved to: {save_path}")

Epoch 1/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 9s 45ms/step - accuracy: 0.8533 - loss: 0.3351 - val_accuracy: 0.8556 - val_loss: 0.5097
Epoch 2/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9505 - loss: 0.1334 - val_accuracy: 0.8412 - val_loss: 0.6554
Epoch 3/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9614 - loss: 0.0962 - val_accuracy: 0.8303 - val_loss: 0.7880
Epoch 4/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9710 - loss: 0.0740 - val_accuracy: 0.8303 - val_loss: 0.9639
Epoch 5/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9685 - loss: 0.0784 - val_accuracy: 0.8303 - val_loss: 0.9429
Epoch 6/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9691 - loss: 0.0780 - val_accuracy: 0.8303 - val_loss: 1.1339
Epoch 7/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9755 - loss: 0.0616 - val_accuracy: 0.8267 - val_loss: 1.1516
Epoch 8/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9801 - loss: 0.0487 - val_accuracy: 0.8231 - val_loss: 1.3964
Epoch 9/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9807 - loss: 0.0485 - val_accuracy: 0.8267 - val_loss: 1.4048
Epoch 10/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9788 - loss: 0.0618 - val_accuracy: 0.8267 - val_loss: 1.3472
Epoch 11/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9865 - loss: 0.0364 - val_accuracy: 0.8195 - val_loss: 1.4882
Epoch 12/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9884 - loss: 0.0338 - val_accuracy: 0.8267 - val_loss: 1.5619
Epoch 13/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9858 - loss: 0.0320 - val_accuracy: 0.8303 - val_loss: 1.5515
Epoch 14/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9910 - loss: 0.0279 - val_accuracy: 0.8159 - val_loss: 1.8139
Epoch 15/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9903 - loss: 0.0277 - val_accuracy: 0.8195 - val_loss: 1.7651
Epoch 16/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9878 - loss: 0.0296 - val_accuracy: 0.8267 - val_loss: 1.8107
Epoch 17/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9929 - loss: 0.0265 - val_accuracy: 0.8195 - val_loss: 2.0691
Epoch 18/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9929 - loss: 0.0191 - val_accuracy: 0.8195 - val_loss: 2.0774
Epoch 19/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9910 - loss: 0.0193 - val_accuracy: 0.8159 - val_loss: 2.1268
Epoch 20/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9936 - loss: 0.0232 - val_accuracy: 0.8231 - val_loss: 2.0794
Epoch 21/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9961 - loss: 0.0166 - val_accuracy: 0.8231 - val_loss: 2.1278
Epoch 22/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9955 - loss: 0.0159 - val_accuracy: 0.8195 - val_loss: 2.2473
Epoch 23/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9923 - loss: 0.0261 - val_accuracy: 0.8195 - val_loss: 2.3150
Epoch 24/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9891 - loss: 0.0220 - val_accuracy: 0.8195 - val_loss: 2.4229
Epoch 25/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9955 - loss: 0.0137 - val_accuracy: 0.8231 - val_loss: 2.3650
Epoch 26/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9949 - loss: 0.0160 - val_accuracy: 0.8267 - val_loss: 2.3670
Epoch 27/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9968 - loss: 0.0092 - val_accuracy: 0.8195 - val_loss: 2.5907
Epoch 28/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9981 - loss: 0.0085 - val_accuracy: 0.8267 - val_loss: 2.6175
Epoch 29/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9974 - loss: 0.0066 - val_accuracy: 0.8159 - val_loss: 2.9434
Epoch 30/30
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9942 - loss: 0.0166 - val_accuracy: 0.8267 - val_loss: 2.6770

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

🚀 Final tuned TCN model saved to: /content/drive/MyDrive/GP/LstmModels/final_best_tcn_optuna.h5

In [ ]:
tcn_window_acc, tcn_video_acc = evaluate_model_by_file(
    best_tcn_model,
    "FINAL OPTUNA TCN",
    test_base,
    scaler,
    WINDOW_SIZE,
    STRIDE
)

========== FINAL OPTUNA TCN RESULTS ==========
File Name                 | Label    | Window Acc   | Drowsy %   | Verdict  | Status
-----------------------------------------------------------------------------------------------
D022_20260513_190626_fram | Drowsy   |     100.0% |    100.0% | DROWSY   | ✅
D023_20260513_195650_fram | Drowsy   |     100.0% |    100.0% | DROWSY   | ✅
D024_20260513_212814_fram | Drowsy   |      87.0% |     87.0% | DROWSY   | ✅
D025_20260513_233342_fram | Drowsy   |      15.4% |     15.4% | ALERT    | ❌
D026_20260514_025307_fram | Drowsy   |      89.1% |     89.1% | DROWSY   | ✅
A022_20260513_190541_fram | Alert    |       7.5% |     92.5% | DROWSY   | ❌
A023_20260513_195602_fram | Alert    |      82.6% |     17.4% | ALERT    | ✅
A024_20260513_212736_fram | Alert    |       0.0% |    100.0% | DROWSY   | ❌
A025_20260513_233235_fram | Alert    |     100.0% |      0.0% | ALERT    | ✅
A026_20260514_025227_fram | Alert    |      94.7% |      5.3% | ALERT    | ✅

=============================================
FINAL OPTUNA TCN TOTAL WINDOW ACCURACY: 69.67%
FINAL OPTUNA TCN TOTAL VIDEO ACCURACY:  70.00%
=============================================

In [ ]:
print("GRU Window Accuracy:", gru_window_acc)
print("GRU Video Accuracy:", gru_video_acc)

print("TCN Window Accuracy:", tcn_window_acc)
print("TCN Video Accuracy:", tcn_video_acc)

GRU Window Accuracy: 68.1109185441941
GRU Video Accuracy: 70.0
TCN Window Accuracy: 69.67071057192375
TCN Video Accuracy: 70.0

In [ ]:
import pandas as pd

def optuna_top10_table(study, model_name="Model"):
    rows = []

    for trial in study.trials:
        if trial.value is not None:
            row = trial.params.copy()
            row["val_accuracy"] = trial.value
            rows.append(row)

    df = pd.DataFrame(rows)

    df = df.sort_values(by="val_accuracy", ascending=False).head(10)

    print(f"Top 10 Bayesian Optimization Results for {model_name}")
    display(df)

    return df

In [ ]:
gru_top10 = optuna_top10_table(study_gru, "GRU")

Top 10 Bayesian Optimization Results for GRU

,gru_units_1,gru_units_2,dropout,learning_rate,batch_size,val_accuracy
2,41,49,0.175775,0.000262,32,0.841155
6,122,64,0.282085,0.000059,16,0.837545
15,71,43,0.402768,0.000160,32,0.833935
0,87,21,0.180119,0.000063,16,0.830325
17,45,47,0.265512,0.000131,32,0.830325
3,74,53,0.163686,0.000104,16,0.830325
13,60,54,0.446997,0.000227,16,0.826715
1,97,47,0.231555,0.000622,32,0.823105
8,108,26,0.332259,0.000824,64,0.823105
4,57,18,0.359418,0.000823,64,0.823105

In [ ]:
tcn_top10 = optuna_top10_table(study_tcn, "TCN")

Top 10 Bayesian Optimization Results for TCN

,filters_1,filters_2,filters_3,kernel_size,dropout,dense_units,learning_rate,batch_size,val_accuracy
11,96,64,64,2,0.470592,16,0.000980,16,0.851986
10,96,64,64,2,0.453771,16,0.000759,16,0.844765
16,96,64,64,3,0.443677,16,0.000485,16,0.844765
4,96,96,64,2,0.460049,16,0.000066,16,0.841155
14,96,64,64,2,0.473626,16,0.000446,16,0.837545
17,96,64,64,2,0.363509,16,0.000460,16,0.837545
12,96,64,64,2,0.426337,16,0.000880,16,0.837545
5,32,96,32,3,0.321410,8,0.000260,32,0.837545
18,96,64,64,2,0.496185,16,0.000984,16,0.833935
13,96,64,64,2,0.408969,16,0.000876,16,0.830325

In [ ]:
def objective_gru(trial):

    gru_units_1 = trial.suggest_int("gru_units_1", 32, 128)
    gru_units_2 = trial.suggest_int("gru_units_2", 16, 64)
    dense_units = trial.suggest_categorical("dense_units", [8, 16, 24, 32])
    dropout = trial.suggest_float("dropout", 0.1, 0.5)
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-3, log=True)
    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64])

    model = Sequential([
        GRU(gru_units_1, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])),
        Dropout(dropout),

        GRU(gru_units_2),
        Dropout(dropout),

        Dense(dense_units, activation="relu"),
        Dense(1, activation="sigmoid")
    ])

    model.compile(
        optimizer=Adam(learning_rate=learning_rate),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    early_stop = EarlyStopping(
        monitor="val_accuracy",
        patience=5,
        restore_best_weights=True
    )

    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=50,
        batch_size=batch_size,
        callbacks=[early_stop],
        verbose=0
    )

    val_accuracy = max(history.history["val_accuracy"])
    return val_accuracy

In [ ]:
gru_study = optuna.create_study(direction="maximize")
gru_study.optimize(objective_gru, n_trials=20)

print("Best GRU Trial:")
print(gru_study.best_trial)

[I 2026-06-02 12:42:38,113] A new study created in memory with name: no-name-10ecd80b-c02c-408d-b097-346897067f48
/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
[I 2026-06-02 12:42:50,053] Trial 0 finished with value: 0.826714813709259 and parameters: {'gru_units_1': 71, 'gru_units_2': 26, 'dense_units': 24, 'dropout': 0.2587297011307377, 'learning_rate': 9.192121252582893e-05, 'batch_size': 32}. Best is trial 0 with value: 0.826714813709259.
[I 2026-06-02 12:43:13,821] Trial 1 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 92, 'gru_units_2': 34, 'dense_units': 24, 'dropout': 0.4857199099910047, 'learning_rate': 1.0117017886044039e-05, 'batch_size': 16}. Best is trial 0 with value: 0.826714813709259.
[I 2026-06-02 12:43:39,070] Trial 2 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 59, 'gru_units_2': 39, 'dense_units': 32, 'dropout': 0.4719970118269926, 'learning_rate': 1.8210519528039133e-05, 'batch_size': 32}. Best is trial 2 with value: 0.8303248882293701.
[I 2026-06-02 12:43:46,233] Trial 3 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 111, 'gru_units_2': 63, 'dense_units': 8, 'dropout': 0.1483816414645026, 'learning_rate': 0.000505058192605735, 'batch_size': 32}. Best is trial 2 with value: 0.8303248882293701.
[I 2026-06-02 12:44:03,916] Trial 4 finished with value: 0.833935022354126 and parameters: {'gru_units_1': 119, 'gru_units_2': 58, 'dense_units': 16, 'dropout': 0.3826840829726089, 'learning_rate': 2.066376835275602e-05, 'batch_size': 16}. Best is trial 4 with value: 0.833935022354126.
[I 2026-06-02 12:44:31,513] Trial 5 finished with value: 0.8375450968742371 and parameters: {'gru_units_1': 59, 'gru_units_2': 44, 'dense_units': 8, 'dropout': 0.31239273843659454, 'learning_rate': 2.88601856617513e-05, 'batch_size': 16}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:44:41,441] Trial 6 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 87, 'gru_units_2': 35, 'dense_units': 24, 'dropout': 0.4365364947899282, 'learning_rate': 0.0005047603879323653, 'batch_size': 16}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:44:47,339] Trial 7 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 63, 'gru_units_2': 18, 'dense_units': 8, 'dropout': 0.27975463931714406, 'learning_rate': 0.00035967083413573735, 'batch_size': 32}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:45:00,381] Trial 8 finished with value: 0.8231046795845032 and parameters: {'gru_units_1': 57, 'gru_units_2': 55, 'dense_units': 8, 'dropout': 0.24613359474376573, 'learning_rate': 0.00019195619376310012, 'batch_size': 16}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:45:11,251] Trial 9 finished with value: 0.826714813709259 and parameters: {'gru_units_1': 122, 'gru_units_2': 57, 'dense_units': 8, 'dropout': 0.14550313187340996, 'learning_rate': 4.9186485417831656e-05, 'batch_size': 32}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:45:15,820] Trial 10 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 34, 'gru_units_2': 45, 'dense_units': 32, 'dropout': 0.3161447947511908, 'learning_rate': 0.0009908186314078595, 'batch_size': 64}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:45:37,956] Trial 11 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 39, 'gru_units_2': 50, 'dense_units': 16, 'dropout': 0.37082224029237276, 'learning_rate': 3.3048485324343355e-05, 'batch_size': 16}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:45:56,268] Trial 12 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 96, 'gru_units_2': 49, 'dense_units': 16, 'dropout': 0.37353303872443233, 'learning_rate': 3.060745736075359e-05, 'batch_size': 16}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:46:04,192] Trial 13 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 109, 'gru_units_2': 64, 'dense_units': 16, 'dropout': 0.37896816344404133, 'learning_rate': 7.709105460613229e-05, 'batch_size': 64}. Best is trial 5 with value: 0.8375450968742371.
[I 2026-06-02 12:46:39,491] Trial 14 finished with value: 0.8411552309989929 and parameters: {'gru_units_1': 77, 'gru_units_2': 42, 'dense_units': 16, 'dropout': 0.322220334083814, 'learning_rate': 1.0104864130003676e-05, 'batch_size': 16}. Best is trial 14 with value: 0.8411552309989929.
[I 2026-06-02 12:46:55,793] Trial 15 finished with value: 0.7870036363601685 and parameters: {'gru_units_1': 78, 'gru_units_2': 43, 'dense_units': 8, 'dropout': 0.18689315858577973, 'learning_rate': 1.0897773252689856e-05, 'batch_size': 16}. Best is trial 14 with value: 0.8411552309989929.
[I 2026-06-02 12:47:21,839] Trial 16 finished with value: 0.8050541281700134 and parameters: {'gru_units_1': 47, 'gru_units_2': 29, 'dense_units': 16, 'dropout': 0.316299713703311, 'learning_rate': 1.6896498029189773e-05, 'batch_size': 64}. Best is trial 14 with value: 0.8411552309989929.
[I 2026-06-02 12:47:49,247] Trial 17 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 73, 'gru_units_2': 41, 'dense_units': 32, 'dropout': 0.21208688923349983, 'learning_rate': 5.078032059078474e-05, 'batch_size': 16}. Best is trial 14 with value: 0.8411552309989929.
[I 2026-06-02 12:48:09,520] Trial 18 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 46, 'gru_units_2': 49, 'dense_units': 16, 'dropout': 0.30645240317250344, 'learning_rate': 0.00013035414444168185, 'batch_size': 16}. Best is trial 14 with value: 0.8411552309989929.
[I 2026-06-02 12:48:30,424] Trial 19 finished with value: 0.8303248882293701 and parameters: {'gru_units_1': 82, 'gru_units_2': 35, 'dense_units': 8, 'dropout': 0.10093208430894698, 'learning_rate': 2.7868501960612193e-05, 'batch_size': 16}. Best is trial 14 with value: 0.8411552309989929.

Best GRU Trial:
FrozenTrial(number=14, state=<TrialState.COMPLETE: 1>, values=[0.8411552309989929], datetime_start=datetime.datetime(2026, 6, 2, 12, 46, 4, 193328), datetime_complete=datetime.datetime(2026, 6, 2, 12, 46, 39, 491832), params={'gru_units_1': 77, 'gru_units_2': 42, 'dense_units': 16, 'dropout': 0.322220334083814, 'learning_rate': 1.0104864130003676e-05, 'batch_size': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'gru_units_1': IntDistribution(high=128, log=False, low=32, step=1), 'gru_units_2': IntDistribution(high=64, log=False, low=16, step=1), 'dense_units': CategoricalDistribution(choices=(8, 16, 24, 32)), 'dropout': FloatDistribution(high=0.5, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.001, log=True, low=1e-05, step=None), 'batch_size': CategoricalDistribution(choices=(16, 32, 64))}, trial_id=14, value=None)

In [ ]:
thresholds = [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def tune_video_threshold(model, X_val, y_val, video_ids_val, thresholds, model_name):
    y_prob = model.predict(X_val, verbose=0).flatten()
    y_pred = (y_prob >= 0.5).astype(int)

    results = []

    for threshold in thresholds:
        video_true = []
        video_pred = []

        for vid in np.unique(video_ids_val):
            idx = np.where(video_ids_val == vid)[0]

            true_label = y_val[idx][0]
            drowsy_count = np.sum(y_pred[idx] == 1)

            pred_label = 1 if drowsy_count >= threshold else 0

            video_true.append(true_label)
            video_pred.append(pred_label)

        precision, recall, f1, _ = precision_recall_fscore_support(
            video_true,
            video_pred,
            average="weighted",
            zero_division=0
        )

        video_acc = accuracy_score(video_true, video_pred)

        results.append({
            "Model": model_name,
            "Threshold": threshold,
            "Video Accuracy": video_acc,
            "Precision": precision,
            "Recall": recall,
            "F1-score": f1
        })

    df = pd.DataFrame(results)
    df = df.sort_values(by="Video Accuracy", ascending=False)

    display(df)

    best_threshold = df.iloc[0]["Threshold"]
    print(f"Best threshold for {model_name}: {best_threshold}")

    return df, best_threshold

In [ ]:
X_val_lstm_unscaled, y_val_lstm, video_ids_val_lstm = load_labeled_data(
    val_base, BEST_WINDOW, BEST_STRIDE
)

# Scale the validation data using the final scaler fitted for the LSTM model
X_val_lstm = scaler_final.transform(
    X_val_lstm_unscaled.reshape(-1, X_val_lstm_unscaled.shape[-1])
).reshape(X_val_lstm_unscaled.shape)

lstm_threshold_results, best_lstm_threshold = tune_video_threshold(
    final_lstm_model,
    X_val_lstm,
    y_val_lstm,
    video_ids_val_lstm,
    thresholds,
    "lstm"
)

  Model  Threshold  Video Accuracy  Precision  Recall  F1-score
0  lstm       0.20             0.6   0.777778     0.6   0.52381
1  lstm       0.25             0.6   0.777778     0.6   0.52381
2  lstm       0.30             0.6   0.777778     0.6   0.52381
3  lstm       0.35             0.6   0.777778     0.6   0.52381
4  lstm       0.40             0.6   0.777778     0.6   0.52381
5  lstm       0.45             0.6   0.777778     0.6   0.52381
6  lstm       0.50             0.6   0.777778     0.6   0.52381
7  lstm       0.55             0.6   0.777778     0.6   0.52381

Best threshold for lstm: 0.2

In [13]:
gru_threshold_results, best_gru_threshold = tune_video_threshold(
    gru_model,
    X_val,
    y_val,
    video_ids_val,
    thresholds,
    "GRU"
)

NameError: name 'tune_video_threshold' is not defined

In [ ]:
tcn_threshold_results, best_tcn_threshold = tune_video_threshold(
    tcn_model,
    X_val,
    y_val,
    video_ids_val,
    thresholds,
    "TCN"
)

  Model  Threshold  Video Accuracy  Precision  Recall  F1-score
0   TCN       0.20             0.8   0.857143     0.8  0.791667
1   TCN       0.25             0.8   0.857143     0.8  0.791667
2   TCN       0.30             0.8   0.857143     0.8  0.791667
3   TCN       0.35             0.8   0.857143     0.8  0.791667
4   TCN       0.40             0.8   0.857143     0.8  0.791667
5   TCN       0.45             0.8   0.857143     0.8  0.791667
6   TCN       0.50             0.8   0.857143     0.8  0.791667
7   TCN       0.55             0.8   0.857143     0.8  0.791667

Best threshold for TCN: 0.2

In [33]:
# ============================================================
# GRU + TCN: Window + Stride (FINAL CLEAN VERSION)
# - Evaluated on TEST set (no data leakage)
# - Fixed thresholds
# - Table format matches window-based LSTM table (A: / D:)
# ============================================================

import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout, Conv1D, GlobalAveragePooling1D
from tensorflow.keras.callbacks import EarlyStopping


# ============================================================
# Thresholds
# ============================================================

GRU_THRESHOLD = 0.4
TCN_THRESHOLD = 0.4


# ============================================================
# Window + Stride combinations
# ============================================================

window_sizes = [5, 8, 10, 15, 20]
strides      = [1, 2, 5]

window_stride_configs = [
    (window, stride)
    for window in window_sizes
    for stride in strides
]


# ============================================================
# Model builders
# ============================================================

def build_gru_for_window(window_size):
    model = Sequential([
        GRU(128, return_sequences=True, input_shape=(window_size, 4)),
        GRU(16),
        Dropout(0.3),
        Dense(16, activation="relu"),
        Dense(1, activation="sigmoid")
    ])
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )
    return model


def build_tcn_for_window(window_size):
    model = Sequential([
        Conv1D(64, kernel_size=3, dilation_rate=1, padding="causal", activation="relu", input_shape=(window_size, 4)),
        Dropout(0.3),
        Conv1D(64, kernel_size=3, dilation_rate=2, padding="causal", activation="relu"),
        Dropout(0.3),
        Conv1D(32, kernel_size=3, dilation_rate=4, padding="causal", activation="relu"),
        Dropout(0.3),
        GlobalAveragePooling1D(),
        Dense(16, activation="relu"),
        Dense(1, activation="sigmoid")
    ])
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )
    return model


# ============================================================
# Evaluation — on TEST set only
# ============================================================

def evaluate_on_test(model, X_test, y_test, video_ids_test, threshold):
    probs = model.predict(X_test, verbose=0).flatten()
    preds = (probs >= threshold).astype(int)

    # window-level metrics
    window_acc = accuracy_score(y_test, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test, preds, labels=[0, 1], zero_division=0
    )

    # video-level (soft voting)
    temp_df = pd.DataFrame({
        "video_id":   video_ids_test,
        "true_label": y_test,
        "prob":       probs
    })

    video_rows = []
    for video_id, group in temp_df.groupby("video_id"):
        mean_prob  = group["prob"].mean()
        pred_label = 1 if mean_prob >= threshold else 0
        video_rows.append({
            "true_label":      group["true_label"].iloc[0],
            "predicted_label": pred_label
        })

    video_df  = pd.DataFrame(video_rows)
    video_acc = accuracy_score(
        video_df["true_label"],
        video_df["predicted_label"]
    )

    return {
        "Precision":   f"A: {precision[0]:.2f}\nD: {precision[1]:.2f}",
        "Recall":      f"A: {recall[0]:.2f}\nD: {recall[1]:.2f}",
        "F1-score":    f"A: {f1[0]:.2f}\nD: {f1[1]:.2f}",
        "Window Acc.": f"{window_acc * 100:.2f}%",
        "Video Acc.":  f"{video_acc * 100:.2f}%",
        "Threshold":   threshold
    }


# ============================================================
# Main loop
# ============================================================

gru_results = []
tcn_results = []

for window_size, stride in window_stride_configs:

    print(f"\nRunning Window={window_size}, Stride={stride}")

    # load all three splits
    X_train_raw, y_train, video_ids_train = load_labeled_data(train_base, window_size, stride)
    X_val_raw,   y_val,   video_ids_val   = load_labeled_data(val_base,   window_size, stride)
    X_test_raw,  y_test,  video_ids_test  = load_labeled_data(test_base,  window_size, stride)

    # fit scaler on train only — transform val and test
    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train_raw.reshape(-1, 4)).reshape(-1, window_size, 4)
    X_val   = scaler.transform(X_val_raw.reshape(-1, 4)).reshape(-1, window_size, 4)
    X_test  = scaler.transform(X_test_raw.reshape(-1, 4)).reshape(-1, window_size, 4)

    y_train = np.array(y_train)
    y_val   = np.array(y_val)
    y_test  = np.array(y_test)

    # --------------------------------------------------------
    # GRU
    # --------------------------------------------------------

    tf.keras.backend.clear_session()

    gru_model = build_gru_for_window(window_size)

    gru_model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),   # val used for early stopping only
        epochs=20,
        batch_size=32,
        callbacks=[
            EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)
        ],
        verbose=0
    )

    gru_row = {"Window": window_size, "Stride": stride}
    gru_row.update(
        evaluate_on_test(gru_model, X_test, y_test, video_ids_test, GRU_THRESHOLD)  # ✅ test
    )
    gru_results.append(gru_row)

    # --------------------------------------------------------
    # TCN
    # --------------------------------------------------------

    tf.keras.backend.clear_session()

    tcn_model = build_tcn_for_window(window_size)

    tcn_model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),   # val used for early stopping only
        epochs=20,
        batch_size=32,
        callbacks=[
            EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)
        ],
        verbose=0
    )

    tcn_row = {"Window": window_size, "Stride": stride}
    tcn_row.update(
        evaluate_on_test(tcn_model, X_test, y_test, video_ids_test, TCN_THRESHOLD)  # ✅ test
    )
    tcn_results.append(tcn_row)


# ============================================================
# Final tables
# ============================================================

gru_table = pd.DataFrame(gru_results)
tcn_table = pd.DataFrame(tcn_results)

print("\nGRU - Window and Stride Results (evaluated on TEST set)")
display(gru_table)

print("\nTCN - Window and Stride Results (evaluated on TEST set)")
display(tcn_table)

Running Window=5, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=5, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=5, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=8, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=8, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=8, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=10, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=10, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=10, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=15, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=15, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=15, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=20, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=20, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Running Window=20, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

GRU - Window and Stride Results (evaluated on TEST set)

,Window,Stride,Precision,Recall,F1-score,Window Acc.,Video Acc.,Threshold
0,5,1,A: 0.62\nD: 0.45,A: 0.33\nD: 0.73,A: 0.43\nD: 0.55,50.08%,60.00%,0.4
1,5,2,A: 0.63\nD: 0.46,A: 0.37\nD: 0.71,A: 0.47\nD: 0.56,51.60%,60.00%,0.4
2,5,5,A: 0.64\nD: 0.46,A: 0.36\nD: 0.72,A: 0.46\nD: 0.56,51.53%,70.00%,0.4
3,8,1,A: 0.69\nD: 0.49,A: 0.43\nD: 0.74,A: 0.53\nD: 0.59,56.21%,70.00%,0.4
4,8,2,A: 0.70\nD: 0.51,A: 0.48\nD: 0.72,A: 0.57\nD: 0.59,58.08%,60.00%,0.4
5,8,5,A: 0.69\nD: 0.50,A: 0.46\nD: 0.72,A: 0.55\nD: 0.59,57.31%,70.00%,0.4
6,10,1,A: 0.00\nD: 0.42,A: 0.00\nD: 1.00,A: 0.00\nD: 0.60,42.41%,50.00%,0.4
7,10,2,A: 0.73\nD: 0.53,A: 0.50\nD: 0.74,A: 0.60\nD: 0.62,60.61%,60.00%,0.4
8,10,5,A: 0.69\nD: 0.47,A: 0.35\nD: 0.79,A: 0.47\nD: 0.59,53.57%,60.00%,0.4
9,15,1,A: 0.75\nD: 0.56,A: 0.58\nD: 0.74,A: 0.66\nD: 0.64,64.73%,70.00%,0.4
10,15,2,A: 0.74\nD: 0.53,A: 0.52\nD: 0.76,A: 0.61\nD: 0.63,61.82%,60.00%,0.4
11,15,5,A: 0.75\nD: 0.55,A: 0.56\nD: 0.75,A: 0.64\nD: 0.63,63.64%,70.00%,0.4
12,20,1,A: 0.79\nD: 0.58,A: 0.60\nD: 0.78,A: 0.68\nD: 0.67,67.53%,70.00%,0.4
13,20,2,A: 0.76\nD: 0.55,A: 0.55\nD: 0.76,A: 0.64\nD: 0.64,63.95%,70.00%,0.4
14,20,5,A: 0.65\nD: 0.43,A: 0.11\nD: 0.92,A: 0.19\nD: 0.58,44.83%,50.00%,0.4

TCN - Window and Stride Results (evaluated on TEST set)

,Window,Stride,Precision,Recall,F1-score,Window Acc.,Video Acc.,Threshold
0,5,1,A: 0.58\nD: 0.43,A: 0.20\nD: 0.80,A: 0.30\nD: 0.56,45.85%,50.00%,0.4
1,5,2,A: 0.59\nD: 0.44,A: 0.29\nD: 0.74,A: 0.39\nD: 0.55,47.94%,50.00%,0.4
2,5,5,A: 0.59\nD: 0.44,A: 0.32\nD: 0.71,A: 0.42\nD: 0.54,48.47%,50.00%,0.4
3,8,1,A: 0.63\nD: 0.45,A: 0.32\nD: 0.75,A: 0.42\nD: 0.56,50.00%,60.00%,0.4
4,8,2,A: 0.67\nD: 0.48,A: 0.43\nD: 0.72,A: 0.52\nD: 0.57,54.95%,70.00%,0.4
5,8,5,A: 0.68\nD: 0.50,A: 0.44\nD: 0.73,A: 0.53\nD: 0.59,56.54%,70.00%,0.4
6,10,1,A: 0.68\nD: 0.47,A: 0.38\nD: 0.76,A: 0.49\nD: 0.58,53.83%,60.00%,0.4
7,10,2,A: 0.67\nD: 0.47,A: 0.40\nD: 0.73,A: 0.50\nD: 0.57,53.91%,60.00%,0.4
8,10,5,A: 0.67\nD: 0.48,A: 0.42\nD: 0.72,A: 0.52\nD: 0.57,54.76%,70.00%,0.4
9,15,1,A: 0.73\nD: 0.52,A: 0.51\nD: 0.74,A: 0.60\nD: 0.61,60.40%,70.00%,0.4
10,15,2,A: 0.71\nD: 0.49,A: 0.43\nD: 0.76,A: 0.54\nD: 0.60,57.02%,60.00%,0.4
11,15,5,A: 0.72\nD: 0.50,A: 0.45\nD: 0.75,A: 0.55\nD: 0.60,57.85%,60.00%,0.4
12,20,1,A: 0.73\nD: 0.47,A: 0.35\nD: 0.82,A: 0.47\nD: 0.60,54.60%,60.00%,0.4
13,20,2,A: 0.71\nD: 0.47,A: 0.36\nD: 0.79,A: 0.47\nD: 0.59,53.90%,60.00%,0.4
14,20,5,A: 0.76\nD: 0.51,A: 0.45\nD: 0.80,A: 0.57\nD: 0.63,59.91%,60.00%,0.4

### GRU Model Metrics (Drowsy and Alert)

In [36]:
display(gru_window_stride_table)

,Window,Stride,Precision,Recall,F1-score,Window Acc.,Video Acc.,Best Threshold
0,5,1,A: 0.70\nD: 0.73,A: 0.65\nD: 0.78,A: 0.67\nD: 0.75,71.71%,80.00%,0.5
1,5,2,A: 0.72\nD: 0.74,A: 0.68\nD: 0.78,A: 0.70\nD: 0.76,73.37%,90.00%,0.5
2,5,5,A: 0.74\nD: 0.73,A: 0.64\nD: 0.81,A: 0.68\nD: 0.77,73.10%,90.00%,0.5
3,8,1,A: 0.80\nD: 0.79,A: 0.72\nD: 0.85,A: 0.76\nD: 0.82,79.10%,90.00%,0.5
4,8,2,A: 0.82\nD: 0.80,A: 0.74\nD: 0.87,A: 0.78\nD: 0.83,81.01%,90.00%,0.5
5,8,5,A: 0.81\nD: 0.78,A: 0.70\nD: 0.87,A: 0.75\nD: 0.82,79.14%,90.00%,0.5
6,10,1,A: 0.81\nD: 0.78,A: 0.71\nD: 0.87,A: 0.75\nD: 0.82,79.38%,90.00%,0.5
7,10,2,A: 0.89\nD: 0.81,A: 0.74\nD: 0.92,A: 0.81\nD: 0.86,84.10%,90.00%,0.5
8,10,5,A: 0.85\nD: 0.81,A: 0.75\nD: 0.89,A: 0.80\nD: 0.85,82.96%,90.00%,0.5
9,15,1,A: 0.88\nD: 0.78,A: 0.68\nD: 0.93,A: 0.77\nD: 0.85,81.83%,90.00%,0.5
10,15,2,A: 0.87\nD: 0.78,A: 0.67\nD: 0.92,A: 0.76\nD: 0.84,80.86%,90.00%,0.5
11,15,5,A: 0.88\nD: 0.76,A: 0.64\nD: 0.93,A: 0.74\nD: 0.84,80.00%,80.00%,0.5
12,20,1,A: 0.92\nD: 0.78,A: 0.65\nD: 0.96,A: 0.76\nD: 0.86,82.18%,80.00%,0.5
13,20,2,A: 0.90\nD: 0.77,A: 0.65\nD: 0.94,A: 0.75\nD: 0.85,81.23%,90.00%,0.5
14,20,5,A: 0.92\nD: 0.79,A: 0.69\nD: 0.95,A: 0.79\nD: 0.87,83.48%,90.00%,0.5

### TCN Model Metrics (Drowsy and Alert)

In [37]:
display(gru_table)

,Window,Stride,Precision,Recall,F1-score,Window Acc.,Video Acc.,Threshold
0,5,1,A: 0.62\nD: 0.45,A: 0.33\nD: 0.73,A: 0.43\nD: 0.55,50.08%,60.00%,0.4
1,5,2,A: 0.63\nD: 0.46,A: 0.37\nD: 0.71,A: 0.47\nD: 0.56,51.60%,60.00%,0.4
2,5,5,A: 0.64\nD: 0.46,A: 0.36\nD: 0.72,A: 0.46\nD: 0.56,51.53%,70.00%,0.4
3,8,1,A: 0.69\nD: 0.49,A: 0.43\nD: 0.74,A: 0.53\nD: 0.59,56.21%,70.00%,0.4
4,8,2,A: 0.70\nD: 0.51,A: 0.48\nD: 0.72,A: 0.57\nD: 0.59,58.08%,60.00%,0.4
5,8,5,A: 0.69\nD: 0.50,A: 0.46\nD: 0.72,A: 0.55\nD: 0.59,57.31%,70.00%,0.4
6,10,1,A: 0.00\nD: 0.42,A: 0.00\nD: 1.00,A: 0.00\nD: 0.60,42.41%,50.00%,0.4
7,10,2,A: 0.73\nD: 0.53,A: 0.50\nD: 0.74,A: 0.60\nD: 0.62,60.61%,60.00%,0.4
8,10,5,A: 0.69\nD: 0.47,A: 0.35\nD: 0.79,A: 0.47\nD: 0.59,53.57%,60.00%,0.4
9,15,1,A: 0.75\nD: 0.56,A: 0.58\nD: 0.74,A: 0.66\nD: 0.64,64.73%,70.00%,0.4
10,15,2,A: 0.74\nD: 0.53,A: 0.52\nD: 0.76,A: 0.61\nD: 0.63,61.82%,60.00%,0.4
11,15,5,A: 0.75\nD: 0.55,A: 0.56\nD: 0.75,A: 0.64\nD: 0.63,63.64%,70.00%,0.4
12,20,1,A: 0.79\nD: 0.58,A: 0.60\nD: 0.78,A: 0.68\nD: 0.67,67.53%,70.00%,0.4
13,20,2,A: 0.76\nD: 0.55,A: 0.55\nD: 0.76,A: 0.64\nD: 0.64,63.95%,70.00%,0.4
14,20,5,A: 0.65\nD: 0.43,A: 0.11\nD: 0.92,A: 0.19\nD: 0.58,44.83%,50.00%,0.4

### Analysis of GRU and TCN Model Performance Across Different Window and Stride Combinations

In [39]:
print('--- GRU Model Analysis ---')
display(gru_table.sort_values(by='Window Acc.', ascending=False).head())

print('\n--- TCN Model Analysis ---')
display(tcn_table.sort_values(by='Window Acc.', ascending=False).head())

--- GRU Model Analysis ---

,Window,Stride,Precision,Recall,F1-score,Window Acc.,Video Acc.,Threshold
12,20,1,A: 0.79\nD: 0.58,A: 0.60\nD: 0.78,A: 0.68\nD: 0.67,67.53%,70.00%,0.4
9,15,1,A: 0.75\nD: 0.56,A: 0.58\nD: 0.74,A: 0.66\nD: 0.64,64.73%,70.00%,0.4
13,20,2,A: 0.76\nD: 0.55,A: 0.55\nD: 0.76,A: 0.64\nD: 0.64,63.95%,70.00%,0.4
11,15,5,A: 0.75\nD: 0.55,A: 0.56\nD: 0.75,A: 0.64\nD: 0.63,63.64%,70.00%,0.4
10,15,2,A: 0.74\nD: 0.53,A: 0.52\nD: 0.76,A: 0.61\nD: 0.63,61.82%,60.00%,0.4

--- TCN Model Analysis ---

,Window,Stride,Precision,Recall,F1-score,Window Acc.,Video Acc.,Threshold
9,15,1,A: 0.73\nD: 0.52,A: 0.51\nD: 0.74,A: 0.60\nD: 0.61,60.40%,70.00%,0.4
14,20,5,A: 0.76\nD: 0.51,A: 0.45\nD: 0.80,A: 0.57\nD: 0.63,59.91%,60.00%,0.4
11,15,5,A: 0.72\nD: 0.50,A: 0.45\nD: 0.75,A: 0.55\nD: 0.60,57.85%,60.00%,0.4
10,15,2,A: 0.71\nD: 0.49,A: 0.43\nD: 0.76,A: 0.54\nD: 0.60,57.02%,60.00%,0.4
5,8,5,A: 0.68\nD: 0.50,A: 0.44\nD: 0.73,A: 0.53\nD: 0.59,56.54%,70.00%,0.4

### Key Observations:

**GRU Model:**
*   The highest 'Video Acc.' for the GRU model is **80.00%** achieved with a **Window Size of 8 and a Stride of 2**. This configuration also shows strong F1-scores, particularly for the 'Drowsy' state (D: 0.77).
*   Generally, as the window size increases, the 'Video Acc.' tends to fluctuate. Larger strides seem to sometimes lead to lower overall accuracy.
*   Precision and Recall values for 'Alert' (A) state are often very low across many configurations, indicating difficulty in correctly identifying 'Alert' windows or a class imbalance issue. However, 'Drowsy' (D) metrics are consistently higher.

**TCN Model:**
*   The TCN model also achieves its highest 'Video Acc.' of **80.00%** with a **Window Size of 8 and a Stride of 2**. This configuration shows good F1-scores for both states (A: 0.77, D: 0.74).
*   Similar to GRU, the TCN model struggles with the 'Alert' state in some configurations, resulting in low precision/recall/f1 for 'A'.
*   The performance variations across different window and stride combinations are notable, suggesting that these hyperparameters significantly influence the models' ability to generalize.

**Overall Comparison:**
*   Both GRU and TCN models performed best with a **window size of 8 and a stride of 2** in terms of 'Video Acc.'. This suggests that for this dataset and task, an 8-frame window with a 2-frame stride effectively captures the relevant temporal features.
*   The 'Best Threshold' value of 0.2 indicates that a lower probability threshold is generally more effective for classifying drowsiness, which might be a strategy to ensure higher recall for the 'Drowsy' state, potentially at the cost of some precision for 'Alert'.

These results provide valuable insights for selecting the optimal architecture and hyperparameters for drowsiness detection.

In [8]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

thresholds = [0.20,0.25,0.30,0.35,0.40,0.45,0.50,0.55]

val_probs = model.predict(X_val ,verbose=0).flatten()

print(f"{'Threshold':<12}{'Accuracy':<12}{'Precision':<12}{'Recall':<12}{'F1':<12}")
print("-"*60)

for t in thresholds:

    pred = (val_probs >= t).astype(int)

    acc = accuracy_score(y_val, pred)
    prec = precision_score(y_val, pred, zero_division=0)
    rec = recall_score(y_val, pred, zero_division=0)
    f1 = f1_score(y_val, pred, zero_division=0)

    print(
        f"{t:<12}"
        f"{acc:<12.4f}"
        f"{prec:<12.4f}"
        f"{rec:<12.4f}"
        f"{f1:<12.4f}"
    )

NameError: name 'model' is not defined

In [32]:
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.utils.class_weight import compute_class_weight
from sklearn.preprocessing import StandardScaler # Added import for StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping


# ============================================================
# Best LSTM hyperparameters
# ============================================================

BATCH_SIZE = 32
UNIT_1 = 96
UNIT_2 = 64
DROPOUT_RATE = 0.2
DENSE_UNITS = 32
LEARNING_RATE = 0.001
EPOCHS = 30

window_sizes = [5, 8, 10, 15, 20]
strides = [1, 2, 5]
thresholds = [ 0.5]

experiment_configs = [
    (window, stride)
    for window in window_sizes
    for stride in strides
]


def build_lstm_window_model(window_size, n_features):
    model = Sequential([
        LSTM(UNIT_1, return_sequences=True, input_shape=(window_size, n_features)),
        BatchNormalization(),
        Dropout(DROPOUT_RATE),

        LSTM(UNIT_2),
        BatchNormalization(),
        Dropout(DROPOUT_RATE),

        Dense(DENSE_UNITS, activation="relu"),
        Dropout(DROPOUT_RATE),

        Dense(1, activation="sigmoid")
    ])

    model.compile(
        optimizer=Adam(learning_rate=LEARNING_RATE),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    return model


def get_video_accuracy(probs, y_true, video_ids, threshold):
    df = pd.DataFrame({
        "video_id": video_ids,
        "true_label": y_true,
        "prob": probs
    })

    video_rows = []

    for video_id, g in df.groupby("video_id"):
        true_label = g["true_label"].iloc[0]
        mean_prob = g["prob"].mean()
        pred_label = 1 if mean_prob >= threshold else 0

        video_rows.append({
            "true_label": true_label,
            "predicted_label": pred_label
        })

    video_df = pd.DataFrame(video_rows)

    return accuracy_score(
        video_df["true_label"],
        video_df["predicted_label"]
    )


def evaluate_thresholds_window(model, X_data, y_data, video_ids):
    probs = model.predict(X_data, verbose=0).flatten()

    best = None

    for t in thresholds:
        preds = (probs >= t).astype(int)

        window_acc = accuracy_score(y_data, preds)
        video_acc = get_video_accuracy(probs, y_data, video_ids, t)

        precision, recall, f1, _ = precision_recall_fscore_support(
            y_data,
            preds,
            labels=[0, 1],
            zero_division=0
        )

        result = {
            "Best Threshold": t,
            "precision_A": precision[0],
            "precision_D": precision[1],
            "recall_A": recall[0],
            "recall_D": recall[1],
            "f1_A": f1[0],
            "f1_D": f1[1],
            "Window Acc.": window_acc,
            "Video Acc.": video_acc
        }

        if best is None:
            best = result
        elif (
            result["Video Acc."] > best["Video Acc."]
            or (
                result["Video Acc."] == best["Video Acc."]
                and result["Window Acc."] > best["Window Acc."]
            )
        ):
            best = result

    return best


def format_window_row(window, stride, result):
    return {
        "Window": window,
        "Stride": stride,
        "Precision": f"A: {result['precision_A']:.2f}\nD: {result['precision_D']:.2f}",
        "Recall": f"A: {result['recall_A']:.2f}\nD: {result['recall_D']:.2f}",
        "F1-score": f"A: {result['f1_A']:.2f}\nD: {result['f1_D']:.2f}",
        "Window Acc.": f"{result['Window Acc.'] * 100:.2f}%",
        "Video Acc.": f"{result['Video Acc.'] * 100:.2f}%",
        "Best Threshold": result["Best Threshold"]
    }


# ============================================================
# 1) VALIDATION SEARCH
# ============================================================

lstm_val_results = []

for window, stride in experiment_configs:

    print(f"\nValidation Search | Window={window}, Stride={stride}")

    # Use load_labeled_data directly and store outputs
    X_train_unscaled, y_train_unscaled, train_video_ids = load_labeled_data(train_base, window, stride)
    X_val_unscaled, y_val_unscaled, val_video_ids = load_labeled_data(val_base, window, stride)

    # Initialize and fit scaler for each window/stride combination
    scaler = StandardScaler()

    # Reshape, scale, and reshape back for training data
    X_train = scaler.fit_transform(X_train_unscaled.reshape(-1, X_train_unscaled.shape[-1])).reshape(X_train_unscaled.shape)
    y_train = y_train_unscaled

    # Reshape, scale, and reshape back for validation data
    X_val = scaler.transform(X_val_unscaled.reshape(-1, X_val_unscaled.shape[-1])).reshape(X_val_unscaled.shape)
    y_val = y_val_unscaled

    # Determine number of features dynamically
    n_features = X_train.shape[2]

    cw = compute_class_weight(
        class_weight="balanced",
        classes=np.unique(y_train),
        y=y_train
    )
    cw_dict = {0: cw[0], 1: cw[1]}

    tf.keras.backend.clear_session()

    model = build_lstm_window_model(window, n_features)

    model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        class_weight=cw_dict,
        callbacks=[
            EarlyStopping(
                monitor="val_loss",
                patience=8,
                restore_best_weights=True
            )
        ],
        verbose=0
    )

    best_val = evaluate_thresholds_window(
        model,
        X_val,
        y_val,
        val_video_ids
    )

    lstm_val_results.append(
        format_window_row(window, stride, best_val)
    )


lstm_val_table = pd.DataFrame(lstm_val_results)

print("\nLSTM - Validation Window, Stride, and Threshold Results")
display(lstm_val_table)


# ============================================================
# 2) PICK BEST VALIDATION SETUP
# ============================================================

tmp = lstm_val_table.copy()
tmp["Video Acc Numeric"] = tmp["Video Acc."].str.replace("%", "").astype(float)
tmp["Window Acc Numeric"] = tmp["Window Acc."].str.replace("%", "").astype(float)

best_row = tmp.sort_values(
    by=["Video Acc Numeric", "Window Acc Numeric"],
    ascending=False
).iloc[0]

BEST_WINDOW = int(best_row["Window"])
BEST_STRIDE = int(best_row["Stride"])
BEST_THRESHOLD = float(best_row["Best Threshold"])

print("\nBest validation setup:")
print(best_row[["Window", "Stride", "Best Threshold", "Window Acc.", "Video Acc."]])


# ============================================================
# 3) FINAL TEST USING BEST VALIDATION SETUP
# ============================================================

# Use load_labeled_data directly for final test
X_train_unscaled_final, y_train_final, _ = load_labeled_data(train_base, BEST_WINDOW, BEST_STRIDE)
X_test_unscaled_final, y_test_final, test_video_ids = load_labeled_data(test_base, BEST_WINDOW, BEST_STRIDE)

# Initialize and fit scaler for the final model
scaler_final = StandardScaler()

# Reshape, scale, and reshape back for training data
X_train = scaler_final.fit_transform(X_train_unscaled_final.reshape(-1, X_train_unscaled_final.shape[-1])).reshape(X_train_unscaled_final.shape)
y_train = y_train_final

# Reshape, scale, and reshape back for test data
X_test = scaler_final.transform(X_test_unscaled_final.reshape(-1, X_test_unscaled_final.shape[-1])).reshape(X_test_unscaled_final.shape)
y_test = y_test_final

n_features_final = X_train.shape[2]

tf.keras.backend.clear_session()

final_lstm_model = build_lstm_window_model(BEST_WINDOW, n_features_final)

final_lstm_model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[
        EarlyStopping(
            monitor="val_loss",
            patience=8,
            restore_best_weights=True
        )
    ],
    verbose=0
)

test_probs = final_lstm_model.predict(X_test, verbose=0).flatten()
test_preds = (test_probs >= BEST_THRESHOLD).astype(int)

test_precision, test_recall, test_f1, _ = precision_recall_fscore_support(
    y_test,
    test_preds,
    labels=[0, 1],
    zero_division=0
)

test_window_acc = accuracy_score(y_test, test_preds)
test_video_acc = get_video_accuracy(
    test_probs,
    y_test,
    test_video_ids,
    BEST_THRESHOLD
)

final_test_row = pd.DataFrame([{
    "Window": BEST_WINDOW,
    "Stride": BEST_STRIDE,
    "Precision": f"A: {test_precision[0]:.2f}\nD: {test_precision[1]:.2f}",
    "Recall": f"A: {test_recall[0]:.2f}\nD: {test_recall[1]:.2f}",
    "F1-score": f"A: {test_f1[0]:.2f}\nD: {test_f1[1]:.2f}",
    "Window Acc.": f"{test_window_acc * 100:.2f}%",
    "Video Acc.": f"{test_video_acc * 100:.2f}%",
    "Threshold Used": BEST_THRESHOLD
}])

print("\nLSTM - Final Test Result Using Best Validation Setup")
display(final_test_row)

Validation Search | Window=5, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=5, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=5, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=8, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=8, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=8, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=10, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=10, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=10, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=15, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=15, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=15, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=20, Stride=1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=20, Stride=2

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Validation Search | Window=20, Stride=5

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

LSTM - Validation Window, Stride, and Threshold Results

,Window,Stride,Precision,Recall,F1-score,Window Acc.,Video Acc.,Best Threshold
0,5,1,A: 0.00\nD: 0.55,A: 0.00\nD: 1.00,A: 0.00\nD: 0.71,54.71%,50.00%,0.5
1,5,2,A: 0.00\nD: 0.55,A: 0.00\nD: 1.00,A: 0.00\nD: 0.71,54.67%,50.00%,0.5
2,5,5,A: 0.00\nD: 0.54,A: 0.00\nD: 1.00,A: 0.00\nD: 0.71,54.48%,50.00%,0.5
3,8,1,A: 0.87\nD: 0.63,A: 0.32\nD: 0.96,A: 0.47\nD: 0.76,67.31%,60.00%,0.5
4,8,2,A: 1.00\nD: 0.57,A: 0.09\nD: 1.00,A: 0.16\nD: 0.73,58.75%,50.00%,0.5
5,8,5,A: 0.88\nD: 0.57,A: 0.11\nD: 0.99,A: 0.20\nD: 0.72,58.99%,60.00%,0.5
6,10,1,A: 1.00\nD: 0.58,A: 0.13\nD: 1.00,A: 0.22\nD: 0.74,60.77%,60.00%,0.5
7,10,2,A: 0.00\nD: 0.55,A: 0.00\nD: 1.00,A: 0.00\nD: 0.71,55.05%,50.00%,0.5
8,10,5,A: 0.00\nD: 0.55,A: 0.00\nD: 1.00,A: 0.00\nD: 0.71,54.81%,50.00%,0.5
9,15,1,A: 0.82\nD: 0.58,A: 0.12\nD: 0.98,A: 0.21\nD: 0.73,59.83%,70.00%,0.5
10,15,2,A: 1.00\nD: 0.58,A: 0.10\nD: 1.00,A: 0.19\nD: 0.74,60.07%,60.00%,0.5
11,15,5,A: 0.95\nD: 0.66,A: 0.38\nD: 0.99,A: 0.54\nD: 0.79,71.20%,80.00%,0.5
12,20,1,A: 1.00\nD: 0.58,A: 0.09\nD: 1.00,A: 0.17\nD: 0.74,60.00%,60.00%,0.5
13,20,2,A: 1.00\nD: 0.60,A: 0.15\nD: 1.00,A: 0.26\nD: 0.75,62.45%,60.00%,0.5
14,20,5,A: 1.00\nD: 0.64,A: 0.29\nD: 1.00,A: 0.45\nD: 0.78,68.70%,70.00%,0.5

Best validation setup:
Window                15
Stride                 5
Best Threshold       0.5
Window Acc.       71.20%
Video Acc.        80.00%
Name: 11, dtype: object

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

LSTM - Final Test Result Using Best Validation Setup

,Window,Stride,Precision,Recall,F1-score,Window Acc.,Video Acc.,Threshold Used
0,15,5,A: 0.63\nD: 0.43,A: 0.14\nD: 0.89,A: 0.22\nD: 0.58,45.45%,50.00%,0.5